import 'package:equatable/equatable.dart';

enum NewLessonType { language, school }

enum NewLessonStatus { draft, active, completed }

class NewLesson extends Equatable {
  const NewLesson({
    required this.id,
    required this.userId,
    required this.lessonType,
    required this.contentType,
    required this.difficulty,
    required this.title,
    this.content,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String userId;
  final NewLessonType lessonType;

  /// For language lessons: the language name (e.g. 'English', 'Spanish').
  /// For school lessons: the subject name (e.g. 'Mathematics', 'Science').
  final String contentType;

  final String difficulty;
  final String title;

  /// Optional JSONB lesson content generated by AI.
  final Map<String, dynamic>? content;

  final NewLessonStatus status;
  final DateTime createdAt;
  final DateTime updatedAt;

  NewLesson copyWith({
    String? id,
    String? userId,
    NewLessonType? lessonType,
    String? contentType,
    String? difficulty,
    String? title,
    Map<String, dynamic>? content,
    NewLessonStatus? status,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return NewLesson(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      lessonType: lessonType ?? this.lessonType,
      contentType: contentType ?? this.contentType,
      difficulty: difficulty ?? this.difficulty,
      title: title ?? this.title,
      content: content ?? this.content,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        userId,
        lessonType,
        contentType,
        difficulty,
        title,
        content,
        status,
        createdAt,
        updatedAt,
      ];
}
